# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0004_bootstrap4carousel_full_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carouselslide',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, mode='both', null=True, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='bootstrap4carouselslide',
            name='carousel_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Slide image'),
        ),
    ]
