# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0005_auto_20190403_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carouselslide',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
