# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_bootstrap4.contrib.bootstrap4_carousel.models
import filer.fields.file
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('bootstrap4_carousel', '0006_bootstrap4carouselslide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carouselslide',
            name='animate_title',
            field=models.BooleanField(default=False, verbose_name='Animate Title'),
        ),
        migrations.AddField(
            model_name='bootstrap4carouselslide',
            name='carousel_video',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Use MP4 videos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='filer.File', validators=[djangocms_bootstrap4.contrib.bootstrap4_carousel.models.Bootstrap4CarouselSlide.validate_mp4_file], verbose_name='Slide video background'),
        ),
        migrations.AlterField(
            model_name='bootstrap4carouselslide',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, colors={'#2B3B46': 'dark', '#323B50': 'grey', '#919FA6': 'cool grey', '#CBCBCB': 'medium-grey', '#FBDB4C': 'maize', '#f5f5f5': 'light-grey', '#ffffff': 'white'}, mode='choice', null=True, verbose_name='Background Color'),
        ),
    ]
