# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 15:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0007_auto_20190604_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carouselslide',
            name='carousel_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide video background url'),
        ),
        migrations.AlterField(
            model_name='bootstrap4carouselslide',
            name='carousel_video',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Use MP4 videos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='filer.File', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Slide video background'),
        ),
    ]
