# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-05 12:54
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0009_auto_20190605_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4carouselslide',
            name='carousel_video',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Use MP4 videos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.File', verbose_name='Slide video background'),
        ),
    ]
