# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0010_auto_20190605_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carouselslide',
            name='carousel_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide video background url'),
        ),
    ]
