# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0011_bootstrap4carouselslide_carousel_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carouselslide',
            name='carousel_style',
            field=models.CharField(default='default', help_text='This is the template that will be used for the component.', max_length=255, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='bootstrap4carousel',
            name='carousel_style',
            field=models.CharField(default='default', help_text='This is the template that will be used for the component.', max_length=255, verbose_name='Template'),
        ),
    ]
