# Generated by Django 2.2.9 on 2020-01-29 12:02

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('bootstrap4_carousel', '0013_auto_20190709_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carousel',
            name='carousel_background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='bootstrap4carouselslide',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, mode='both', null=True, verbose_name='Background Color'),
        ),
    ]
