# Generated by Django 2.2.9 on 2020-01-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0014_auto_20200129_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4carousel',
            name='carousel_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
