# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_icon.fields
import filer.fields.image
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('bootstrap4_grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, null=True, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='col_bg_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='display_title',
            field=models.BooleanField(default=False, verbose_name='Display Title'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, null=True, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row_bg_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='display_title',
            field=models.BooleanField(default=False, verbose_name='Display Title'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='icon',
            field=djangocms_icon.fields.Icon(blank=True, default='', max_length=255, null=True, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
