# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0002_auto_20190206_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='full_width',
            field=models.BooleanField(default=False, verbose_name='Show Full Width'),
        ),
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='parallax',
            field=models.BooleanField(default=False, verbose_name='Parallax'),
        ),
    ]
