# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0003_auto_20190306_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridrow',
            name='layout',
            field=models.CharField(blank=True, choices=[('columns', 'Columns'), ('rows', 'Rows'), ('hero', 'Hero'), ('articles', 'Articles')], help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
    ]
