# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0005_auto_20190514_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='layout',
            field=models.CharField(blank=True, choices=[('', 'Configure this list in settings (GRID_COL_LAYOUT_CHOICES)')], help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
    ]
