# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0008_auto_20190604_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4gridrow',
            name='layout',
            field=models.CharField(blank=True, choices=[('color_cols', 'Full Width - Color Columns'), ('banner_dark', 'Banner - Dark'), ('banner_yellow', 'Banner - Yellow'), ('title_yellow_italic', 'Title - Yellow Italic'), ('title_yellow_regular', 'Title - Yellow Regular'), ('title_yellow_caps', 'Title - Yellow Caps'), ('title_dark_italic', 'Title - Dark Italic'), ('title_dark_regular', 'Title - Dark Regular'), ('title_dark_caps', 'Title - Dark Caps'), ('title_color_bar', 'Title - Color Bar')], help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
    ]
