# Generated by Django 2.2.10 on 2020-05-21 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0009_auto_20190610_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4gridcolumn',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='col_bg_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcolumn',
            name='layout',
            field=models.CharField(blank=True, help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridrow',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='row_bg_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridrow',
            name='layout',
            field=models.CharField(blank=True, help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
    ]
