# Generated by Django 2.2.10 on 2020-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0011_bootstrap4gridrow_background_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='lg_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='md_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='sm_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='xl_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='xs_hide',
            field=models.BooleanField(default=False),
        ),
    ]
