# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_link', '0003_add_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4link',
            name='no_link',
            field=models.BooleanField(default=False, verbose_name='No Link'),
        ),
    ]
