# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_link.validators
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('bootstrap4_link', '0004_bootstrap4link_no_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4link',
            name='file_link',
            field=filer.fields.file.FilerFileField(blank=True, help_text='If provided links a file from the filer app.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='File link'),
        ),
        migrations.AlterField(
            model_name='bootstrap4link',
            name='external_link',
            field=models.CharField(blank=True, help_text='Provide a link to an external source.', max_length=2040, validators=[djangocms_link.validators.IntranetURLValidator(intranet_host_re=None)], verbose_name='External link'),
        ),
    ]
