# Generated by Django 2.2.10 on 2020-02-13 05:16

from django.db import migrations, models
import djangocms_bootstrap4.contrib.bootstrap4_link.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_link', '0005_auto_20190709_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4link',
            name='modal_id',
            field=models.CharField(blank=True, default='', help_text='Do not include a preceding "#" symbol.', max_length=60, verbose_name='Modal Id'),
        ),
        migrations.AlterField(
            model_name='bootstrap4link',
            name='external_link',
            field=models.CharField(blank=True, help_text='Provide a link to an external source.', max_length=2040, validators=[djangocms_bootstrap4.contrib.bootstrap4_link.validators.LocalORIntranetURLValidator()], verbose_name='External link'),
        ),
    ]
