# Generated by Django 2.2.10 on 2020-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_collapse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4collapse',
            name='layout',
            field=models.CharField(blank=True, help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
    ]
