# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_boxout', '0002_bootstrap4boxout_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4boxout',
            name='full_width',
            field=models.BooleanField(default=False, verbose_name='Show Full Width'),
        ),
    ]
