# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_boxout', '0003_bootstrap4boxout_full_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4boxout',
            name='layout',
            field=models.CharField(blank=True, help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='bootstrap4boxout',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
