# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_picture', '0003_auto_20190205_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4picture',
            name='use_responsive_image',
            field=models.CharField(choices=[('inherit', 'Let settings.DJANGOCMS_PICTURE_RESPONSIVE_IMAGES decide'), ('yes', 'Yes'), ('no', 'No')], default='inherit', help_text='Uses responsive image technique to choose better image to display based upon screen viewport. This configuration only applies to uploaded images (external pictures will not be affected). ', max_length=7, verbose_name='Use responsive image'),
        ),
        migrations.AlterField(
            model_name='bootstrap4picture',
            name='use_automatic_scaling',
            field=models.BooleanField(default=True, help_text='Uses the placeholder dimensions to automatically calculate the size.', verbose_name='Automatic scaling'),
        ),
    ]
