# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 04:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('bootstrap4_picture', '0004_auto_20190219_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4picture',
            name='svg',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.File', verbose_name='SVG Image'),
        ),
    ]
