# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_bootstrap4.contrib.bootstrap4_link.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_picture', '0006_auto_20190710_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4picture',
            name='link_url',
            field=models.CharField(blank=True, help_text='Wraps the image in a link to an URL.', max_length=2040, null=True, validators=[djangocms_bootstrap4.contrib.bootstrap4_link.validators.LocalORIntranetURLValidator()], verbose_name='link URL'),
        ),
    ]
