# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_cta', '0002_bootstrap4cta_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4cta',
            name='layout',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('yellow_corner', 'Yellow Corner')], help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
    ]
