# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_bootstrap4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap4Modal',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_modal_bootstrap4modal', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('modal_id', models.CharField(blank=True, max_length=255, verbose_name='Modal ID')),
                ('layout', models.CharField(blank=True, help_text='Select a layout', max_length=255, verbose_name='Layout')),
                ('attributes', djangocms_bootstrap4.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
