# Generated by Django 2.2.10 on 2020-03-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_modal', '0002_auto_20200305_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4modal',
            name='cookie_settings',
            field=models.CharField(blank=True, choices=[('', 'Show every time (default)'), ('once-per-session', 'Cap at one view per session'), ('once-ever', 'Show once ever')], default='', max_length=255, verbose_name='Cookie settings'),
        ),
    ]
