# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_tabs', '0002_auto_20190521_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4tab',
            name='full_width',
            field=models.BooleanField(default=False, verbose_name='Full Width'),
        ),
        migrations.AlterField(
            model_name='bootstrap4tab',
            name='show_title',
            field=models.BooleanField(default=False, verbose_name='Show title'),
        ),
        migrations.AlterField(
            model_name='bootstrap4tab',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
