# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 09:43
from __future__ import unicode_literals

from django.db import migrations
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_tabs', '0003_auto_20190603_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4tab',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, colors={'#2B3B46': 'dark', '#323B50': 'grey', '#919FA6': 'cool grey', '#CBCBCB': 'medium-grey', '#FBDB4C': 'maize', '#f5f5f5': 'light-grey', '#ffffff': 'white'}, mode='choice', null=True, verbose_name='Background Color'),
        ),
    ]
