# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_content', '0002_added_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4blockquote',
            name='quote_origin_company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='bootstrap4blockquote',
            name='quote_origin_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='bootstrap4blockquote',
            name='quote_origin_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role'),
        ),
    ]
