# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_content', '0003_auto_20181011_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootstrap4blockquote',
            name='quote_origin',
        ),
    ]
