# Generated by Django 2.2.10 on 2020-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_content', '0004_remove_bootstrap4blockquote_quote_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4blockquote',
            name='layout',
            field=models.CharField(blank=True, default='', help_text='Select a layout', max_length=255, verbose_name='Layout'),
        ),
    ]
